"""Strict, read-only evidence boundary for the Q6.2 post-hoc outcome audit.

Only the historical panel's safe exports and domain SQLite facts are decoded.
Decision journals, raw responses and prompts are never decoded. All regular
source files are streamed for SHA256, including journals, without exporting
their contents. This module imports only the standard library and cannot create
a model client, migrate a world, repair evidence, or write an output file.
"""
from __future__ import annotations

import hashlib
import json
import math
import re
import sqlite3
from collections import Counter
from contextlib import contextmanager
from pathlib import Path

PROTOCOL_VERSION = "q62_fixed_state_panel_v2"
PROTOCOL_HASH = "b66217fa18ce8740deec38334b157ff35f00455d8d2b431dd0b48531debffcc6"
EXECUTION_COMMIT = "ae2123f50beaaca6bcac2dcca8e34659bd0a8b24"
CONDITIONS = ("A_RAW", "B_FEASIBLE")
FAMILIES = frozenset({"OWNERSHIP", "POST_MEAL_NEED", "MEDIA_PROGRESS",
                      "ACTIVITY_LOCATION", "MEAL_PAYMENT", "MEAL_SUPPLY"})
OBJECTS = ("food_bread", "food_meal", "game_a", "series_a")
LOCATIONS = frozenset({"home", "restaurant", "office", "park"})
ACTIVITIES = frozenset({"CHORES", "LEISURE", "MEAL", "PERSONAL_CARE", "PLAY",
                        "SLEEP", "TRAVEL", "WATCH", "WORK"})
TOP_FILES = frozenset({"session.json", "session.sqlite3", "summary.json", "cells.jsonl",
                       "manifest.json", "cleanup.json", "paired_comparison.json",
                       "config.json", "report_zh.md"})
CELL_FILES = frozenset({"initial_projection.json", "initial_state.json", "initial_audit.json",
                        "final_state.json", "world.sqlite3", "decision_journal.jsonl"})
PLAN_FIELDS = ("cell_id", "condition", "family", "order", "pair_id", "pair_order",
               "repeat", "scenario_id", "within_pair_order", "candidate_count",
               "candidate_hash", "prompt_chars", "prompt_hash")
FLAG_FIELDS = ("activity_completed", "catalog_valid", "client_call_attempted",
               "http_response_observed", "intent_registered", "invariants_valid",
               "proposal_in_feasible_set", "rule_checked", "service_contract_valid",
               "start_accepted", "strict_json_valid", "local_call_settled")
INT_FIELDS = ("events_count", "input_tokens", "output_tokens", "reasoning_tokens",
              "simulation_minutes", "provider_requests", "micro_steps", "http_status",
              "timeout_streak_before", "timeout_streak_after")
COUNT_FIELDS = ("activity_completed", "catalog_valid", "client_call_attempted",
                "commitment_failed", "http_response_observed", "intent_registered",
                "intent_send_unknown", "invariants_valid", "not_run", "outside_catalog",
                "planned", "rule_checked", "rule_rejected", "service_contract_valid",
                "start_accepted", "strict_json_valid", "unknown", "valid_proposal_unknown",
                "valid_proposals")


class SourceEvidenceError(ValueError):
    """Fixed diagnostics identify a field, never include a source value/text."""

    def __init__(self, field_id: str):
        # field IDs are generated by this module, not taken from input values.
        self.field_id = field_id
        super().__init__("SOURCE_EVIDENCE_MISMATCH:" + field_id)


def canonical_digest(value: object) -> str:
    data = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"),
                      allow_nan=False).encode("utf-8")
    return hashlib.sha256(data).hexdigest()


def _check(condition: bool, field: str) -> None:
    if not condition:
        raise SourceEvidenceError(field)


def _json(path: Path, field: str) -> object:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, ValueError):
        raise SourceEvidenceError(field) from None


def _rows(path: Path, field: str) -> list[dict]:
    try:
        rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines()]
        _check(all(isinstance(row, dict) for row in rows), field)
        return rows
    except (OSError, UnicodeError, ValueError):
        raise SourceEvidenceError(field) from None


def _int(value: object, field: str, *, maximum: int | None = None) -> int:
    _check(type(value) is int and value >= 0, field)
    _check(maximum is None or value <= maximum, field)
    return value


def _number(value: object, field: str) -> int | float:
    _check(type(value) in (int, float) and math.isfinite(value) and value >= 0, field)
    return value


def _enum(value: object, allowed: object, field: str) -> str:
    _check(isinstance(value, str) and value in allowed, field)
    return value


def _hash(value: object, field: str) -> str:
    _check(isinstance(value, str) and re.fullmatch(r"[0-9a-f]{64}", value) is not None, field)
    return value


def source_hashes(source: str | Path) -> dict[str, str]:
    """Hash all regular source files; reject symlinks and credential filenames.

    The file allowlist prevents a stray .env from being read even for hashing.
    A changed listing is a failure, not silently relabelled as 297 files.
    """
    source = Path(source)
    _check(source.is_dir() and not source.is_symlink(), "source.directory")
    output = {}
    for path in sorted(source.rglob("*")):
        _check(not path.is_symlink(), "source.symlink")
        if not path.is_file():
            continue
        relative = path.relative_to(source).as_posix()
        parts = relative.split("/")
        safe = relative in TOP_FILES or (
            len(parts) == 3 and parts[0] == "cells"
            and re.fullmatch(r"c(?:00[1-9]|0[1-3][0-9]|04[0-8])", parts[1]) is not None
            and parts[2] in CELL_FILES)
        _check(safe, "source.file_allowlist")
        try:
            with path.open("rb") as stream:
                output[relative] = hashlib.file_digest(stream, "sha256").hexdigest()
        except OSError:
            raise SourceEvidenceError("source.hash_read") from None
    _check(len(output) == 297, "source.file_count")
    return output


def verify_source_unchanged(source: str | Path, before_hashes: dict[str, str]) -> dict:
    after = source_hashes(source)
    _check(after == before_hashes, "source.hashes_unchanged")
    return {"SOURCE_FILES_UNCHANGED": "PASS", "file_count": len(after),
            "before": dict(before_hashes), "after": after,
            "listing_digest": canonical_digest(after), "new_real_provider_requests": 0}


def sanitize_state(value: object, field: str = "state") -> dict:
    """Whitelist the historical projected state, not arbitrary source strings."""
    _check(isinstance(value, dict), field)
    output = {key: _int(value.get(key), field + "." + key,
                        maximum=1000 if key in ("hunger_milli", "energy_milli") else None)
              for key in ("minute", "money_cents", "hunger_milli", "energy_milli", "state_version")}
    output["location"] = _enum(value.get("location"), LOCATIONS, field + ".location")
    _check(value.get("commitment") is None, field + ".commitment")
    output["commitment"] = None
    inventory = value.get("inventory")
    _check(isinstance(inventory, dict) and set(inventory) == set(OBJECTS), field + ".inventory")
    output["inventory"] = {key: _int(inventory[key], field + ".inventory") for key in OBJECTS}
    play = value.get("play_minutes")
    _check(isinstance(play, dict) and set(play) == {"game_a"}, field + ".play_minutes")
    output["play_minutes"] = {"game_a": _int(play["game_a"], field + ".play_minutes")}
    media = value.get("media_progress")
    _check(isinstance(media, dict) and set(media) == {"series_a"}, field + ".media_progress")
    series = media["series_a"]
    _check(isinstance(series, dict), field + ".media_progress")
    total = _int(series.get("total_episodes"), field + ".total_episodes")
    _check(total == 120, field + ".total_episodes")
    watched = series.get("watched")
    _check(isinstance(watched, list) and all(type(n) is int and 1 <= n <= total for n in watched)
           and watched == sorted(set(watched)), field + ".watched")
    progress = {"total_episodes": total, "watched": list(watched)}
    for key in ("offsets", "view_counts"):
        entries = series.get(key)
        _check(isinstance(entries, dict), field + "." + key)
        _check(all(isinstance(k, str) and k.isdecimal() and 1 <= int(k) <= total
                   for k in entries), field + "." + key)
        progress[key] = {k: _int(v, field + "." + key, maximum=30 if key == "offsets" else None)
                         for k, v in entries.items()}
    episode = series.get("next_episode")
    expected = next((n for n in range(1, total + 1) if n not in watched), None)
    _check(episode == expected and (episode is None or type(episode) is int), field + ".next_episode")
    progress["next_episode"] = episode
    output["media_progress"] = {"series_a": progress}
    return output


def _plan(value: object, field: str) -> dict:
    _check(isinstance(value, dict), field)
    output = {}
    for key, pattern in (("cell_id", r"c[0-9]{3}"), ("pair_id", r"p[0-9]{3}"),
                         ("scenario_id", r"s[0-9]{2}")):
        item = value.get(key)
        _check(isinstance(item, str) and re.fullmatch(pattern, item) is not None, field + "." + key)
        output[key] = item
    output["condition"] = _enum(value.get("condition"), CONDITIONS, field + ".condition")
    output["family"] = _enum(value.get("family"), FAMILIES, field + ".family")
    for key in ("order", "pair_order", "repeat", "within_pair_order", "candidate_count", "prompt_chars"):
        output[key] = _int(value.get(key), field + "." + key)
    for key in ("candidate_hash", "prompt_hash"):
        output[key] = _hash(value.get(key), field + "." + key)
    return output


def sanitize_cell(value: dict, field: str = "cell") -> dict:
    output = _plan(value, field)
    output["status"] = _enum(value.get("status"), {"DECISION_ACCEPTED", "PROVIDER_TIMEOUT"},
                             field + ".status")
    for key in FLAG_FIELDS:
        item = value.get(key)
        _check(item is None or type(item) is bool, field + "." + key)
        output[key] = item
    for key in INT_FIELDS:
        item = value.get(key)
        output[key] = None if item is None else _int(item, field + "." + key)
    output["latency_seconds"] = _number(value.get("latency_seconds"), field + ".latency_seconds")
    for key in ("before_state", "after_state"):
        output[key] = sanitize_state(value.get(key), field + "." + key)
    output["final_state_hash"] = _hash(value.get("final_state_hash"), field + ".final_state_hash")
    for key, allowed in (("proposal_activity", ACTIVITIES), ("proposal_target", set(OBJECTS) | LOCATIONS),
                         ("provider_model", {"glm-5.3"}), ("requested_model", {"ark-code-latest"}),
                         ("commitment_status", {"COMPLETED"})):
        item = value.get(key)
        output[key] = None if item is None else _enum(item, allowed, field + "." + key)
    timeout = output["status"] == "PROVIDER_TIMEOUT"
    output["effects_observed"] = not timeout
    _check(output["client_call_attempted"] is True and output["provider_requests"] == 1,
           field + ".application_attempt")
    _check(output["invariants_valid"] is True, field + ".invariants")
    if timeout:
        _check(all(output[k] is None for k in ("proposal_activity", "proposal_target",
                                               "activity_completed", "http_response_observed",
                                               "input_tokens", "output_tokens", "reasoning_tokens")),
               field + ".timeout_missing")
        _check(output["before_state"] == output["after_state"], field + ".timeout_no_action")
    else:
        _check(all(output[k] is True for k in ("activity_completed", "http_response_observed",
                                               "strict_json_valid", "catalog_valid", "rule_checked",
                                               "start_accepted")), field + ".accepted_evidence")
        _check(output["http_status"] == 200 and output["proposal_activity"] is not None
               and output["provider_model"] == "glm-5.3",
               field + ".accepted_response")
    _check(output["simulation_minutes"] == output["after_state"]["minute"] - output["before_state"]["minute"],
           field + ".simulation_minutes")
    return output


@contextmanager
def readonly_sqlite(path: str | Path):
    """No StateStore constructor, migrations, writes, WAL or journal creation."""
    path = Path(path)
    _check(path.is_file() and not path.is_symlink(), "sqlite.source")
    _check(not Path(str(path) + "-wal").exists(), "sqlite.active_wal")
    connection = None
    try:
        connection = sqlite3.connect(path.resolve().as_uri() + "?mode=ro&immutable=1",
                                     uri=True, isolation_level=None)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA query_only=ON")
        yield connection
    except sqlite3.Error:
        raise SourceEvidenceError("sqlite.read_only_schema") from None
    finally:
        if connection is not None:
            connection.close()


def _database_json(text: str, field: str) -> object:
    try:
        return json.loads(text)
    except (TypeError, ValueError):
        raise SourceEvidenceError(field) from None


def _world(path: Path, cell: dict, fixture_event_count: int) -> dict:
    with readonly_sqlite(path) as db:
        _check(db.execute("PRAGMA integrity_check").fetchone()[0] == "ok", "world.integrity")
        meta = {row["key"]: row["value"] for row in db.execute(
            "SELECT key,value FROM meta WHERE key IN ('schema_version','minute','rule_parameters')")}
        _check(meta.get("schema_version") == "1", "world.schema")
        actors = [_database_json(row[0], "world.actor_json") for row in db.execute(
            "SELECT data FROM actors ORDER BY id")]
        objects = []
        for row in db.execute("SELECT data,stock,available FROM objects ORDER BY id"):
            item = _database_json(row[0], "world.object_json")
            _check(isinstance(item, dict), "world.object")
            objects.append({**item, "stock": row[1], "available": bool(row[2])})
        links = [{"actor_id": row[0], "object_id": row[1], "state": _database_json(row[2], "world.link_json")}
                 for row in db.execute("SELECT actor_id,object_id,data FROM links ORDER BY actor_id,object_id")]
        commitments = [_database_json(row[0], "world.commitment_json") for row in db.execute(
            "SELECT data FROM commitments ORDER BY id")]
        snapshot = {"minute": int(meta["minute"]), "rules": _database_json(meta["rule_parameters"], "world.rules"),
                    "actors": actors, "objects": objects, "links": links, "commitments": commitments}
        _check(canonical_digest(snapshot) == cell["final_state_hash"], "world.final_state_hash")
        _check(len(actors) == 1 and actors[0].get("actor_id") == 1, "world.actor_count")
        actor = actors[0]
        by_object = {obj["object_id"]: obj for obj in objects}
        _check(set(by_object) == set(OBJECTS), "world.catalog")
        by_link = {link["object_id"]: link["state"] for link in links}
        _check(all(link["actor_id"] == 1 and link["object_id"] in OBJECTS for link in links), "world.links")
        series = by_link.get("series_a", {})
        watched = series.get("watched", [])
        projected = {"minute": snapshot["minute"], "state_version": actor["version"],
                     **{key: actor[key] for key in ("money_cents", "hunger_milli", "energy_milli", "location")},
                     "commitment": None,
                     "inventory": {obj: by_link.get(obj, {}).get("quantity", 0) for obj in OBJECTS},
                     "play_minutes": {"game_a": by_link.get("game_a", {}).get("play_minutes", 0)},
                     "media_progress": {"series_a": {"total_episodes": 120, "watched": watched,
                         "offsets": series.get("offsets", {}), "view_counts": series.get("view_counts", {}),
                         "next_episode": next((n for n in range(1, 121) if n not in watched), None)}}}
        _check(all(item.get("status") not in {"ACTIVE", "PAUSED"} for item in commitments), "world.active_commitment")
        _check(sanitize_state(projected, "world.projected") == cell["after_state"], "world.after_state")
        final = _json(path.parent / "final_state.json", "world.final_export")
        _check(canonical_digest(final) == cell["final_state_hash"], "world.final_export_hash")
        event_rows = list(db.execute("SELECT seq,kind,minute,payload FROM events ORDER BY seq"))
        _check(len(event_rows) == cell["events_count"] and fixture_event_count <= len(event_rows), "world.event_count")
        # These are existing deterministic domain ledgers, never decision_attempts
        # or journals that might contain arbitrary model-originated text.
        domain = {"purchased_quantities": {}, "consumed_quantities": {},
                  "execution_event_counts": {}, "work_minutes_before": None,
                  "work_minutes_after": _int(actor.get("work_minutes"), "world.work_minutes"),
                  "calories_kcal_before": None,
                  "calories_kcal_after": _int(actor.get("calories_kcal"), "world.calories")}
        initial_event = _database_json(event_rows[0]["payload"], "world.genesis")
        _check(event_rows[0]["kind"] == "WORLD_CREATED" and isinstance(initial_event, dict), "world.genesis")
        initial_actor = initial_event.get("initial", {}).get("actors", [{}])[0]
        before_calories = _int(initial_actor.get("calories_kcal"), "world.genesis_calories")
        before_work = _int(initial_actor.get("work_minutes"), "world.genesis_work")
        new_calories = new_work = 0
        phases = Counter()
        for index, event in enumerate(event_rows):
            kind = event["kind"]
            if kind not in {"ATE", "PURCHASED", "WORKED", "MOVED", "TIME_ADVANCED"}:
                continue
            payload = _database_json(event["payload"], "world.domain_event")
            _check(isinstance(payload, dict), "world.domain_event")
            allocated = index >= fixture_event_count
            if allocated:
                phases[kind] += 1
            if kind == "ATE":
                calories = _int(payload.get("calories_kcal"), "world.ate_calories")
                if allocated:
                    new_calories += calories
                else:
                    before_calories += calories
            if kind == "WORKED":
                minutes = _int(payload.get("minutes"), "world.work_event_minutes")
                if allocated:
                    new_work += minutes
                else:
                    before_work += minutes
            if allocated and kind in {"ATE", "PURCHASED"}:
                obj = _enum(payload.get("object_id"), OBJECTS, "world.event_object")
                quantity = _int(payload.get("quantity"), "world.event_quantity")
                key = "consumed_quantities" if kind == "ATE" else "purchased_quantities"
                domain[key][obj] = domain[key].get(obj, 0) + quantity
        _check(before_calories + new_calories == domain["calories_kcal_after"], "world.calorie_ledger")
        _check(before_work + new_work == domain["work_minutes_after"], "world.work_ledger")
        domain.update(work_minutes_before=before_work, calories_kcal_before=before_calories,
                      execution_event_counts=dict(sorted(phases.items())))
        for obj in OBJECTS:
            _check(cell["after_state"]["inventory"][obj] - cell["before_state"]["inventory"][obj]
                   == domain["purchased_quantities"].get(obj, 0) - domain["consumed_quantities"].get(obj, 0),
                   "world.inventory_ledger")
        return domain


def _verify_ledger(source: Path, manifest: dict, cells: list[dict], session_id: str) -> None:
    with readonly_sqlite(source / "session.sqlite3") as db:
        _check(db.execute("PRAGMA integrity_check").fetchone()[0] == "ok", "ledger.integrity")
        meta = {row[0]: _database_json(row[1], "ledger.meta") for row in db.execute(
            "SELECT key,value FROM meta WHERE key IN ('schema_version','session_id','manifest','manifest_hash','planned_cells','max_calls','max_calls_per_cell')")}
        _check(meta.get("schema_version") == "q62_fixed_panel_ledger_v1", "ledger.schema")
        _check(meta.get("session_id") == session_id, "ledger.session_id")
        _check(meta.get("manifest") == manifest and meta.get("manifest_hash") == canonical_digest(manifest),
               "ledger.manifest")
        _check(meta.get("planned_cells") == 48 and meta.get("max_calls") == 48
               and meta.get("max_calls_per_cell") == 1, "ledger.budget")
        records = list(db.execute("SELECT ordinal,cell_id,plan,request_id,stage,final_row FROM cells ORDER BY ordinal"))
        _check(len(records) == 48, "ledger.allocation_count")
        for index, (record, cell) in enumerate(zip(records, cells, strict=True), 1):
            field = "ledger.cell." + cell["cell_id"]
            _check(record["ordinal"] == index and record["cell_id"] == cell["cell_id"], field + ".identity")
            _check(_plan(_database_json(record["plan"], field + ".plan_json"), field + ".plan")
                   == {k: cell[k] for k in PLAN_FIELDS}, field + ".plan")
            request_id = "panel:" + canonical_digest([session_id, cell["cell_id"]])
            _check(record["request_id"] == request_id and record["stage"] == "FINAL_ROW", field + ".claim")
            _check(sanitize_cell(_database_json(record["final_row"], field + ".final_json"), field) == cell,
                   field + ".final_row")
        stages = dict(db.execute("SELECT stage,count(*) FROM evidence GROUP BY stage"))
        for stage in ("CALL_INTENT_REGISTERED", "CLIENT_CALL_STARTED", "FINAL_ROW", "WORLD_RESULT_COMMITTED"):
            _check(stages.get(stage) == 48, "ledger.stage." + stage)
        _check(stages.get("RESPONSE_OBSERVED") == 46 and stages.get("PARSE_RESULT") == 46,
               "ledger.response_stages")


def _verify_counts(summary: dict, cells: list[dict], pairs: list[dict], field: str) -> dict:
    counts = {key: sum(cell.get(key) is True for cell in cells) for key in FLAG_FIELDS}
    counts.update(planned=len(cells), valid_proposals=sum(cell["strict_json_valid"] is True
                  and cell["catalog_valid"] is True for cell in cells), rule_rejected=0,
                  commitment_failed=0, not_run=0, unknown=0, outside_catalog=0,
                  valid_proposal_unknown=sum(cell["status"] == "PROVIDER_TIMEOUT" for cell in cells),
                  intent_send_unknown=0)
    safe = {key: counts[key] for key in COUNT_FIELDS}
    _check(summary.get("counts") == safe, field + ".counts")
    pair_counts = summary.get("pair_counts", {})
    _check(pair_counts.get("planned") == 24 and pair_counts.get("complete_scored") == 22
           and pair_counts.get("complete_valid_proposals") == 22
           and pair_counts.get("incomplete_valid_proposals") == 2
           and pair_counts.get("backend_match") == 22 and pair_counts.get("backend_unknown") == 2,
           field + ".pair_counts")
    _check(summary.get("session_termination") == "PANEL_COMPLETED", field + ".termination")
    _check(summary.get("real_provider_requests") == 48, field + ".requests")
    _check(summary.get("status_counts") == {"DECISION_ACCEPTED": 46, "PROVIDER_TIMEOUT": 2},
           field + ".statuses")
    _check(summary.get("actual_backend_distribution") == {"glm-5.3": 46, "UNKNOWN": 2},
           field + ".backends")
    _check(len(pairs) == 24, field + ".pairs")
    return safe


def _pairs(values: object, cells: list[dict]) -> list[dict]:
    _check(isinstance(values, list) and len(values) == 24, "pairs.count")
    output = []
    for index, value in enumerate(values, 1):
        field = "pairs.p" + f"{index:03}"
        _check(isinstance(value, dict) and value.get("pair_id") == f"p{index:03}", field + ".identity")
        arms = [cell for cell in cells if cell["pair_id"] == f"p{index:03}"]
        _check(len(arms) == 2 and {c["condition"] for c in arms} == set(CONDITIONS), field + ".arms")
        a, b = (next(c for c in arms if c["condition"] == condition) for condition in CONDITIONS)
        _check(all(a[key] == b[key] == value.get(key) for key in ("scenario_id", "family", "repeat")),
               field + ".scenario_repeat")
        _check(a["before_state"] == b["before_state"], field + ".initial_state")
        complete = a["effects_observed"] and b["effects_observed"]
        expected = {"pair_id": value["pair_id"], "scenario_id": a["scenario_id"], "family": a["family"],
                    "repeat": a["repeat"], "pair_structure_valid": True,
                    "valid_proposal_pair_complete": complete, "scored_pair_complete": complete,
                    "comparable_scored_pair": complete,
                    "backend_comparability": "BACKEND_MATCH" if complete else "BACKEND_UNKNOWN",
                    "a_status": a["status"], "b_status": b["status"],
                    "a_valid_proposal": True if a["effects_observed"] else None,
                    "b_valid_proposal": True if b["effects_observed"] else None,
                    "a_activity_completed": a["activity_completed"], "b_activity_completed": b["activity_completed"],
                    "incomplete_reasons": ([] if complete else
                        [("A_" if not a["effects_observed"] else "B_") + "PROVIDER_TIMEOUT"])}
        for key, item in expected.items():
            _check(value.get(key) == item, field + "." + key)
        for metric in ("input_tokens", "output_tokens", "reasoning_tokens", "prompt_chars", "latency_seconds"):
            diff = b[metric] - a[metric] if a.get(metric) is not None and b.get(metric) is not None else None
            item = value.get(metric + "_B_minus_A")
            _check(item == diff or (type(item) in (int, float) and diff is not None
                                    and math.isclose(item, diff, rel_tol=1e-12, abs_tol=1e-10)),
                   field + "." + metric)
            expected[metric + "_B_minus_A"] = diff
        output.append(expected)
    _check(sum(pair["scored_pair_complete"] for pair in output) == 22, "pairs.complete_count")
    _check([pair["pair_id"] for pair in output if not pair["scored_pair_complete"]] == ["p014", "p021"],
           "pairs.timeout_identity")
    return output


def _load_verified_session(source: str | Path, recovery: str | Path | None = None,
                           analysis: str | Path | None = None) -> dict:
    """Return only verified, whitelisted evidence; stop on any inconsistency.

    Recovery/analysis default to the existing sibling artifacts, never generated
    from the Chinese report. Missing provenance is a failure, not fake evidence.
    The caller owns a new output directory and performs a final hash check after
    its metrics/report generation with ``verify_source_unchanged``.
    """
    source = Path(source)
    before = source_hashes(source)
    manifest = _json(source / "manifest.json", "manifest.json")
    config = _json(source / "config.json", "config.json")
    session = _json(source / "session.json", "session.json")
    summary = _json(source / "summary.json", "summary.json")
    _check(all(isinstance(item, dict) for item in (manifest, config, session, summary)), "source.metadata_types")
    _check(canonical_digest(config) == PROTOCOL_HASH and manifest.get("protocol") == config
           and manifest.get("protocol_hash") == PROTOCOL_HASH and session.get("protocol_hash") == PROTOCOL_HASH,
           "source.protocol_hash")
    _check(session.get("mode") == "REAL_PROVIDER" and session.get("status") == "PANEL_COMPLETED"
           and session.get("processed_cells") == 48, "source.session_status")
    session_id = session.get("session_id")
    _check(isinstance(session_id, str) and re.fullmatch(r"q62-panel-real-v2-01", session_id) is not None,
           "source.session_id")
    _check(session.get("execution", {}).get("git_commit") == EXECUTION_COMMIT, "source.execution_commit")
    _check(session.get("execution", {}).get("agentsociety_submodule_commit")
           == "670c94fff7c64c4f79b632125f2ccf968155e746", "source.submodule_commit")
    cleanup = _json(source / "cleanup.json", "cleanup.json")
    _check(cleanup == {"cleanup_exception_type": None, "cleanup_local_settled": True,
                       "cleanup_outcome": "CLOSED"}, "source.cleanup")
    rows = _rows(source / "cells.jsonl", "cells.jsonl")
    _check(len(rows) == 48, "cells.count")
    cells = [sanitize_cell(row, f"cells.c{index:03}") for index, row in enumerate(rows, 1)]
    plans = manifest.get("cells")
    _check(isinstance(plans, list) and len(plans) == 48, "manifest.cells")
    for index, (cell, plan) in enumerate(zip(cells, plans, strict=True), 1):
        _check(cell["cell_id"] == f"c{index:03}" and cell["order"] == index, "cells.order")
        _check(_plan(plan, "manifest.plan") == {k: cell[k] for k in PLAN_FIELDS}, "manifest.plan_match")
    _verify_ledger(source, manifest, cells, session_id)
    scenarios = manifest.get("scenarios")
    _check(isinstance(scenarios, list) and len(scenarios) == 12, "manifest.scenarios")
    scenario_map = {s.get("scenario_id"): s for s in scenarios if isinstance(s, dict)}
    _check(set(scenario_map) == {f"s{i:02}" for i in range(1, 13)}, "manifest.scenario_identity")
    frozen = []
    for scenario_id in sorted(scenario_map):
        item = scenario_map[scenario_id]
        safe = {"scenario_id": scenario_id, "family": _enum(item.get("family"), FAMILIES, "scenario.family"),
                "initial_projected_state": sanitize_state(item.get("initial_projected_state"), "scenario.initial")}
        for key in ("candidate_hash", "observation_hash", "state_hash"):
            safe[key] = _hash(item.get(key), "scenario." + key)
        for key in ("candidate_count", "fixture_event_count", "observation_chars", "state_minute", "state_version"):
            safe[key] = _int(item.get(key), "scenario." + key)
        for key in ("prompt_chars", "prompt_bytes", "prompt_hashes"):
            entries = item.get(key)
            _check(isinstance(entries, dict) and set(entries) == set(CONDITIONS), "scenario." + key)
            safe[key] = {condition: (_hash(entries[condition], "scenario.prompt_hash") if key == "prompt_hashes"
                                     else _int(entries[condition], "scenario.prompt_length")) for condition in CONDITIONS}
        options = item.get("executable_options")
        _check(isinstance(options, list) and len(options) == safe["candidate_count"], "scenario.options")
        safe["executable_options"] = []
        for option in options:
            _check(isinstance(option, dict), "scenario.option")
            activity = _enum(option.get("activity"), ACTIVITIES, "scenario.option_activity")
            target = option.get("target")
            safe["executable_options"].append({"activity": activity, "target": None if target is None else
                                               _enum(target, set(OBJECTS) | LOCATIONS, "scenario.option_target")})
        _check(canonical_digest(safe["executable_options"]) == safe["candidate_hash"], "scenario.candidate_hash")
        # Exact frozen protocol hash validates this recipe, not a free-text field.
        recipe = next(s["recipe"] for s in config["scenarios"] if s["scenario_id"] == scenario_id)
        _check(item.get("recipe") == recipe, "scenario.recipe")
        safe["recipe"] = recipe
        frozen.append(safe)
    for cell in cells:
        scenario = scenario_map[cell["scenario_id"]]
        _check(cell["family"] == scenario["family"] and cell["repeat"] in (1, 2), "cell.scenario")
        _check(cell["before_state"] == sanitize_state(scenario["initial_projected_state"]), "cell.fixture_state")
        _check(sanitize_state(_json(source / "cells" / cell["cell_id"] / "initial_state.json", "cell.initial_export"))
               == cell["before_state"], "cell.initial_export")
        initial_audit = _json(source / "cells" / cell["cell_id"] / "initial_audit.json", "cell.initial_audit")
        _check(all(initial_audit.get(key) == cell[key] for key in ("candidate_count", "candidate_hash", "prompt_chars", "prompt_hash")),
               "cell.initial_audit")
        _check(initial_audit.get("state_hash") == scenario["state_hash"]
               and initial_audit.get("observation_hash") == scenario["observation_hash"], "cell.initial_hashes")
        projection = _json(source / "cells" / cell["cell_id"] / "initial_projection.json", "cell.initial_projection")
        _check(projection.get("executable_options") == scenario["executable_options"]
               and projection.get("candidate_digest") == cell["candidate_hash"]
               and projection.get("candidate_count") == cell["candidate_count"]
               and projection.get("observation_digest") == scenario["observation_hash"], "cell.projection")
        _check(initial_audit.get("object_candidates") == scenario.get("object_candidates")
               and projection.get("object_candidates") == len(scenario.get("object_candidates", [])), "cell.object_candidates")
        cell["domain_facts"] = _world(source / "cells" / cell["cell_id"] / "world.sqlite3", cell,
                                      scenario["fixture_event_count"])
    pairs = _pairs(_json(source / "paired_comparison.json", "paired_comparison.json"), cells)
    counts = _verify_counts(summary, cells, pairs, "summary")
    _check(counts["client_call_attempted"] == 48 and counts["http_response_observed"] == 46
           and counts["valid_proposals"] == 46 and counts["activity_completed"] == 46
           and counts["valid_proposal_unknown"] == 2, "source.expected_counts")
    evaluation_root = source.parent.parent
    recovery = Path(recovery) if recovery is not None else evaluation_root / "q6_2_fixed_state_panel_recovery" / session_id
    analysis = Path(analysis) if analysis is not None else evaluation_root / "q62_v2_analysis" / session_id
    recovery_summary = _json(recovery / "summary.json", "recovery.summary")
    _verify_counts(recovery_summary, cells, pairs, "recovery.summary")
    recovered = [sanitize_cell(row, "recovery.cell") for row in _rows(recovery / "cells.jsonl", "recovery.cells")]
    _check([{k: v for k, v in cell.items() if k != "domain_facts"} for cell in cells] == recovered,
           "recovery.cells_match")
    _check(_pairs(_json(recovery / "paired_comparison.json", "recovery.pairs"), cells) == pairs, "recovery.pairs_match")
    proof = _json(recovery / "source_hash_proof.json", "recovery.integrity")
    _check(proof.get("source_files") == 297 and proof.get("source_hashes") == before
           and proof.get("source_all_hashes_unchanged") is True and proof.get("source_modified") is False
           and proof.get("new_provider_requests") == 0, "recovery.source_hashes")
    metadata = _json(recovery / "recovery.json", "recovery.metadata")
    _check(metadata.get("automatic_resume") is False and metadata.get("source_modified") is False
           and metadata.get("new_provider_requests") == 0, "recovery.read_only")
    metrics = _json(analysis / "safe_metrics.json", "analysis.metrics")
    _check(metrics.get("source_session_id") == session_id and metrics.get("source_execution_commit") == EXECUTION_COMMIT
           and metrics.get("protocol_canonical_hash") == PROTOCOL_HASH, "analysis.provenance")
    _check(metrics.get("overall", {}).get("counts") == counts, "analysis.counts")
    _check(metrics.get("pair_counts") == summary.get("pair_counts"), "analysis.pair_counts")
    _check(_pairs(metrics.get("pairs"), cells) == pairs, "analysis.pairs_match")
    _check(metrics.get("additional_provider_requests") == 0 and metrics.get("source_written") is False
           and metrics.get("credential_files_read") == 0, "analysis.read_only")
    _check(all(before.get(key) == value for key, value in metrics.get("source_hashes", {}).items())
           and len(metrics.get("source_hashes", {})) == 6, "analysis.source_hashes")
    previous_integrity = _json(analysis / "source_integrity.json", "analysis.integrity")
    _check(previous_integrity.get("unchanged") is True
           and previous_integrity.get("credential_files_read") == 0
           and previous_integrity.get("provider_requests") == 0
           and previous_integrity.get("before") == previous_integrity.get("after")
           and previous_integrity.get("before") == metrics.get("source_hashes"), "analysis.integrity_match")
    integrity = verify_source_unchanged(source, before)
    integrity.update(SOURCE_SESSION_VERIFIED="PASS", planned_cells=48, planned_pairs=24,
                     fully_scored_pairs=22, world_databases_verified=48,
                     recovery_verified=True, previous_analysis_verified=True,
                     decoded_completion_or_prompt_files=0, credential_files_read=0)
    # No arbitrary source strings or raw metric dictionaries cross this boundary.
    return {"sanitized_cells": cells, "source_integrity": integrity,
            "provenance": {"session_id": session_id, "protocol_version": PROTOCOL_VERSION,
                           "protocol_hash": PROTOCOL_HASH, "execution_commit": EXECUTION_COMMIT,
                           "source": str(source.resolve())},
            "original_metrics": {"counts": counts, "pair_counts": {
                "planned": 24, "complete_scored": 22, "incomplete": 2},
                "original_q62_conclusion": "NO_CLEAR_DIFFERENCE"},
            "paired_comparison": pairs, "protocol": config, "frozen_scenarios": frozen,
            "allocated_cells": [_plan(plan, "manifest.plan") for plan in plans]}


def load_verified_session(source: str | Path, recovery: str | Path | None = None,
                          analysis: str | Path | None = None) -> dict:
    """Read-only strict verifier; malformed input gets a fixed safe diagnostic."""
    try:
        return _load_verified_session(source, recovery, analysis)
    except SourceEvidenceError:
        raise
    except (OSError, ValueError, TypeError, KeyError, IndexError, AttributeError):
        raise SourceEvidenceError("source.malformed_safe_structure") from None
